import OutlineSection from '@/components/custom/OutlineSection'
import { firebaseDb, GeminiAiModel } from '@/config/FirebaseConfig';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { useEffect, useRef, useState, useCallback } from 'react'
import { useParams } from 'react-router-dom'
import type { Project } from '@/pages/workspace/project/outline/Outline';
import SliderFrame from '@/components/custom/SliderFrame';
import AiEditGuide from '@/components/custom/AiEditGuide';
import * as htmlToImage from "html-to-image";
import PptxGenJS from "pptxgenjs";
import { FileDown, InfoIcon, Loader2, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { toast } from "sonner";

const SLIDER_PROMPT = `You are creating a PowerPoint slide based on the AI-generated outline below. Use ALL the information provided to create a comprehensive, professional slide.

**COMPLETE OUTLINE DATA FROM DATABASE:**
This outline was generated by AI based on the user's topic. Use ALL of this information:
- Slide Number: {SLIDE_NO}
- Slide Title/Point: {SLIDE_POINT}
- Slide Content/Outline: {SLIDE_OUTLINE}

**CRITICAL INSTRUCTIONS:**
1. The slide title MUST be: "{SLIDE_POINT}" - use this exactly as the main heading.
2. The slide content MUST be based on: "{SLIDE_OUTLINE}" - this is the detailed outline generated by AI. Use this to create:
   - Main content sections
   - Bullet points
   - Key information
   - Supporting details
3. The slide number is {SLIDE_NO} - you can optionally display this as a slide indicator.

**DESIGN STYLE GUIDELINES:**
{DESIGN_STYLE}

**COLOR PALETTE:**
{COLORS_CODE}

**TECHNICAL REQUIREMENTS:**
1. Create a professional PowerPoint slide that fully represents the outline information above.
2. Use "{SLIDE_POINT}" as the main title/heading (large, prominent, styled according to design guide).
3. Use "{SLIDE_OUTLINE}" to create the body content - break it down into:
   - Clear sections or bullet points
   - Key highlights
   - Supporting information
   - Visual elements that complement the content
4. Follow the design style guide exactly - colors, fonts, layout style.
5. Use the provided color palette - primary, secondary, accent, background colors.
6. Fixed 16:9 layout: 800px width × 500px height (no responsive design).
7. Use Flowbite UI components and TailwindCSS utility classes.
8. Create visually appealing layouts using grid or flexbox.
9. Images must fit within containers without overflow (use object-cover or object-contain).
10. Maintain 16:9 aspect ratio for all elements.
11. Use proper spacing and layout to avoid overlapping elements.

**IMAGE GENERATION (if needed):**
Generate images using ImageKit format:
'https://ik.imagekit.io/ikmedia/ik-genimg-prompt-{imagePrompt}/{altImageName}.jpg'
- {imagePrompt} should describe an image relevant to "{SLIDE_POINT}" and "{SLIDE_OUTLINE}"
- {altImageName} should be a descriptive filename

**HTML STRUCTURE REQUIRED:**
<!-- Slide Content Wrapper (Fixed 16:9 Aspect Ratio) -->
<div class="w-[800px] h-[500px] relative overflow-hidden">
  <!-- 
    Your slide must include:
    1. Title: "{SLIDE_POINT}"
    2. Content based on: "{SLIDE_OUTLINE}"
    3. Visual elements (images, icons, graphics)
    4. Proper styling using the design style and colors
  -->
</div>

**FINAL CHECKLIST:**
✓ Title matches "{SLIDE_POINT}"
✓ Content reflects "{SLIDE_OUTLINE}"
✓ Design style applied correctly
✓ Colors from palette used
✓ 16:9 aspect ratio maintained
✓ No overlay gradients (avoid: absolute inset-0 bg-gradient...)
✓ All content within 800px × 500px container
✓ Professional and visually appealing

Generate ONLY the HTML body content for this one slide. Make it comprehensive, informative, and visually stunning.`


const DUMMY_SLIDER = ` <!-- Slide Content Wrapper (Fixed 16:9 Aspect Ratio) -->
    <div class="w-[800px] h-[500px] relative bg-[#0D0D0D] text-white overflow-hidden">
        <!-- Background Gradient Overlay -->
        <div class="absolute inset-0 bg-gradient-to-br from-[#0D0D0D] to-[#1F1F1F] opacity-70"></div>

        <!-- Grid Layout for Content -->
        <div class="grid grid-cols-2 grid-rows-2 h-full relative z-10">

            <!-- Left Top - Title & Outline -->
            <div class="col-span-1 row-span-1 p-8 flex flex-col justify-start items-start">
                <h1 class="text-4xl font-serif font-bold text-accent mb-4">
                    Welcome to Kravix Studio: The Future of Film
                </h1>
                <p class="text-sm text-gray-300 leading-relaxed">
                    Welcome to our investor pitch for [App Name], an innovative AI Short Film Generator.<br>
                    We are revolutionizing content creation, making filmmaking accessible to everyone.
                </p>
            </div>

            <!-- Right Top - Image/Visual -->
            <div class="col-span-1 row-span-1 p-4 flex justify-end items-start">
                <img src="https://ik.imagekit.io/ikmedia/ik-genimg-prompt-futuristic%20film%20studio%20interior%20black%20gold%20accents/filmStudioAesthetic.jpg" alt="filmStudioAesthetic" class="rounded-lg shadow-lg w-full h-auto object-cover max-h-[200px]">
            </div>

            <!-- Left Bottom - Call to Action/Key Benefit -->
            <div class="col-span-1 row-span-1 p-8 flex flex-col justify-end items-start">
                <div class="bg-[#1F1F1F] bg-opacity-60 backdrop-blur-md rounded-lg p-6">
                    <h2 class="text-2xl font-serif font-semibold mb-2">
                        Unleash Your Creative Vision
                    </h2>
                    <p class="text-gray-200 text-sm leading-relaxed">
                        Transform ideas into stunning short films with the power of AI. No experience needed.
                    </p>
                </div>
            </div>

            <!-- Right Bottom - Slide Number & Subtle Element -->
            <div class="col-span-1 row-span-1 p-8 flex justify-end items-end">
                 <div class="flex items-center space-x-2">
                        <span class="text-gray-400 text-xs font-medium">Slide</span>
                        <span class="text-accent font-bold text-xl">1</span>
                    </div>
                
            </div>

            <!-- Subtle Lighting Effect (Optional) -->
            <div class="absolute inset-0 pointer-events-none">
                <div class="absolute top-1/4 left-1/4 w-32 h-32 bg-accent rounded-full blur-3xl opacity-10"></div>
                <div class="absolute bottom-1/4 right-1/4 w-24 h-24 bg-primary rounded-full blur-2xl opacity-10"></div>
            </div>
        </div>
    </div>`

function Editor() {
  const { id: projectId } = useParams<{ id: string }>();
  const [projectDetail, setProjectDetail] = useState<Project>();
  const [loading, setLoading] = useState(false);
  const [sliders, setSliders] = useState<any>([]);
  const [isSlidesGenerated, setIsSlidesGenerated] = useState<any>();
  const [generatingSlides, setGeneratingSlides] = useState(false);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [downloadLoading, setDownloadLoading] = useState(false);

  const GetProjectDetail = useCallback(async () => {
    if (!projectId) {
      console.error("❌ No projectId provided");
      setLoading(false);
      return;
    }

    try {
      setLoading(true);
      console.log("📥 Fetching project data for ID:", projectId);

      const docRef = doc(firebaseDb, "projects", projectId);
      console.log("📡 Firestore query initiated...");

      const docSnap: any = await getDoc(docRef);
      console.log("📡 Firestore query completed");

      if (!docSnap.exists()) {
        console.error("❌ Project document does not exist in Firestore");
        console.error("  - Project ID:", projectId);
        console.error("  - Collection: projects");
        setLoading(false);
        return;
      }

      const data = docSnap.data();
      console.log("✅ Project document found!");
      console.log("📄 Project data loaded:", JSON.stringify(data, null, 2));

      // Detailed outline checking
      console.log("📋 OUTLINE CHECK:");
      console.log("  - Has outline field:", "outline" in data);
      console.log("  - Outline value:", data.outline);
      console.log("  - Outline type:", typeof data.outline);
      console.log("  - Is array:", Array.isArray(data.outline));
      if (Array.isArray(data.outline)) {
        console.log("  - Outline length:", data.outline.length);
        if (data.outline.length > 0) {
          console.log(
            "  - First outline item:",
            JSON.stringify(data.outline[0], null, 2)
          );
          console.log(
            "  - First item has slideNo:",
            "slideNo" in (data.outline[0] || {})
          );
          console.log(
            "  - First item has slidePoint:",
            "slidePoint" in (data.outline[0] || {})
          );
          console.log(
            "  - First item has outline:",
            "outline" in (data.outline[0] || {})
          );
        }
      }

      console.log("  - Has designStyle:", !!data.designStyle);
      if (data.designStyle) {
        console.log("  - DesignStyle type:", typeof data.designStyle);
        console.log("  - DesignStyle details:", {
          styleName: data.designStyle.styleName,
          hasColors: !!data.designStyle.colors,
          hasDesignGuide: !!data.designStyle.designGuide,
        });
      }
      console.log("  - Has slides:", !!data.slides, data.slides?.length);

      console.log("💾 Setting projectDetail state...");
      setProjectDetail(data as Project);
      console.log("✅ projectDetail state set successfully");
      setLoading(false);
    } catch (error) {
      console.error("❌ Error fetching project detail:", error);
      console.error("❌ Error details:", JSON.stringify(error, null, 2));
      setLoading(false);
      alert(
        `Failed to load project: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }, [projectId]);

  useEffect(() => {
    console.log("🔄 useEffect triggered");
    console.log("  - projectId from URL params:", projectId);
    console.log("  - Current URL:", window.location.pathname);

    if (projectId) {
      console.log("✅ projectId exists, calling GetProjectDetail...");
      GetProjectDetail().catch((error) => {
        console.error("❌ GetProjectDetail failed:", error);
      });
    } else {
      console.warn("⚠️ No projectId found in URL params");
      console.warn("  - Expected format: /workspace/project/{id}/editor");
      console.warn("  - Make sure you're navigating from the outline page");
    }
  }, [projectId, GetProjectDetail]);

  const GenerateSlides = useCallback(async () => {
    if (!projectDetail) {
      console.error("❌ No project detail available");
      return;
    }

    // Validate outline exists and is an array
    if (!projectDetail.outline) {
      console.error("❌ No outline field found in projectDetail");
      console.error("❌ Available fields:", Object.keys(projectDetail));
      return;
    }

    if (!Array.isArray(projectDetail.outline)) {
      console.error(
        "❌ Outline is not an array. Type:",
        typeof projectDetail.outline
      );
      console.error("❌ Outline value:", projectDetail.outline);
      return;
    }

    if (projectDetail.outline.length === 0) {
      console.error("❌ Outline array is empty");
      return;
    }

    if (!projectDetail.designStyle) {
      console.error("❌ No design style found");
      return;
    }

    setGeneratingSlides(true);
    console.log(
      "🚀 Starting slide generation based on outline from database..."
    );
    console.log("  - Outline items count:", projectDetail.outline.length);
    console.log("  - Design style:", projectDetail.designStyle.styleName);
    console.log(
      "  - Full outline array:",
      JSON.stringify(projectDetail.outline, null, 2)
    );

    // Initialize sliders array with empty states - generate ALL slides from outline
    const initialSliders = projectDetail.outline.map(() => ({ code: "" }));
    setSliders(initialSliders);

    try {
      const slidesToGenerate = projectDetail.outline.length;
      for (let index = 0; index < slidesToGenerate; index++) {
        const outlineItem = projectDetail.outline[index];

        if (!outlineItem) {
          console.warn(
            `⚠️ Outline item at index ${index} is undefined, skipping...`
          );
          continue;
        }

        console.log(`\n📋 ===== Slide ${index + 1}/${slidesToGenerate} =====`);
        console.log(
          `📋 Outline item from database:`,
          JSON.stringify(outlineItem, null, 2)
        );
        console.log(`  - Slide No: "${outlineItem.slideNo || "N/A"}"`);
        console.log(`  - Slide Point: "${outlineItem.slidePoint || "N/A"}"`);
        console.log(`  - Outline: "${outlineItem.outline || "N/A"}"`);

        // Validate outline item has required fields
        if (!outlineItem.slidePoint && !outlineItem.outline) {
          console.warn(
            `⚠️ Slide ${index + 1} has no slidePoint or outline, using defaults`
          );
        }

        // Build the prompt with ALL outline information from database
        // These values come directly from the AI-generated outline saved in the database
        const slideNo = outlineItem.slideNo || `${index + 1}`;
        const slidePoint = outlineItem.slidePoint || `Slide ${index + 1}`;
        const slideOutline =
          outlineItem.outline ||
          "Content will be generated based on the topic.";

        // Escape special characters for proper replacement
        const escapedSlidePoint = slidePoint.replace(/"/g, '\\"');
        const escapedSlideOutline = slideOutline.replace(/"/g, '\\"');

        // Build comprehensive prompt using ALL outline data from database
        const prompt = SLIDER_PROMPT.replace(/{SLIDE_NO}/g, slideNo)
          .replace(/{SLIDE_POINT}/g, escapedSlidePoint)
          .replace(/{SLIDE_OUTLINE}/g, escapedSlideOutline)
          .replace(
            "{DESIGN_STYLE}",
            projectDetail.designStyle.designGuide ?? ""
          )
          .replace(
            "{COLORS_CODE}",
            JSON.stringify(projectDetail.designStyle.colors ?? {})
          );

        console.log(
          `🧠 Generating slide ${
            index + 1
          } using COMPLETE outline from database:`
        );
        console.log(`  📌 Title: "${slidePoint}"`);
        console.log(
          `  📝 Content: "${slideOutline.substring(0, 150)}${
            slideOutline.length > 150 ? "..." : ""
          }"`
        );
        console.log(`  🔢 Slide No: ${slideNo}`);
        console.log(`  📏 Prompt length: ${prompt.length} characters`);
        console.log(
          `  ✅ All outline fields (slideNo, slidePoint, outline) are being used in the prompt`
        );

        await GeminiSlideCall(prompt, index); // wait for one slide to finish before next
        console.log(`✅ Finished slide ${index + 1}`);
      }

      console.log("🎉 All slides generated!");
      setIsSlidesGenerated(Date.now());
    } catch (error) {
      console.error("❌ Error during slide generation:", error);
    } finally {
      setGeneratingSlides(false);
    }
  }, [projectDetail]);

  useEffect(() => {
    if (!projectDetail) {
      console.log("⏳ Waiting for projectDetail to load...");
      return;
    }

    console.log("\n🔍 ===== CHECKING SLIDE GENERATION CONDITIONS =====");
    console.log("  - Has outline:", !!projectDetail.outline);
    console.log("  - Outline length:", projectDetail.outline?.length || 0);
    console.log("  - Has designStyle:", !!projectDetail.designStyle);
    console.log(
      "  - Has slides:",
      !!projectDetail.slides,
      projectDetail.slides?.length || 0
    );

    if (projectDetail.designStyle) {
      console.log("  - DesignStyle type:", typeof projectDetail.designStyle);
      console.log(
        "  - DesignStyle is object:",
        typeof projectDetail.designStyle === "object"
      );
      if (typeof projectDetail.designStyle === "string") {
        console.error(
          "  - ⚠️ WARNING: designStyle is a string, not an object! This is the problem."
        );
      } else {
        console.log(
          "  - DesignStyle styleName:",
          projectDetail.designStyle.styleName
        );
      }
    }

    // Check if designStyle is a string (old format) - if so, refetch data
    if (
      projectDetail.designStyle &&
      typeof projectDetail.designStyle === "string"
    ) {
      console.warn(
        "⚠️ designStyle is a string, not an object. Refetching data..."
      );
      setTimeout(() => {
        GetProjectDetail();
      }, 1000);
      return;
    }

    // Check if slides exist and have content
    if (
      projectDetail.slides &&
      Array.isArray(projectDetail.slides) &&
      projectDetail.slides.length > 0
    ) {
      console.log("✅ Slides already exist, loading them");
      setSliders(projectDetail.slides);
    } else if (
      projectDetail.outline &&
      Array.isArray(projectDetail.outline) &&
      projectDetail.outline.length > 0 &&
      projectDetail.designStyle &&
      typeof projectDetail.designStyle === "object"
    ) {
      console.log(
        "✅ All conditions met! Starting automatic slide generation..."
      );
      console.log("  - Outline items:", projectDetail.outline.length);
      console.log("  - Design style:", projectDetail.designStyle.styleName);
      GenerateSlides();
    } else {
      console.warn("⚠️ Cannot auto-generate slides - missing requirements:");
      if (!projectDetail.outline) {
        console.error("  ❌ Missing outline field");
      } else if (!Array.isArray(projectDetail.outline)) {
        console.error(
          "  ❌ Outline is not an array. Type:",
          typeof projectDetail.outline
        );
      } else if (projectDetail.outline.length === 0) {
        console.error("  ❌ Outline array is empty");
      }
      if (!projectDetail.designStyle) {
        console.error("  ❌ Missing designStyle");
      } else if (typeof projectDetail.designStyle === "string") {
        console.error(
          "  ❌ designStyle is a string (old format), not an object!"
        );
      }
      console.log(
        "💡 You can manually trigger generation using the 'Generate Slides' button"
      );
    }
  }, [projectDetail, GenerateSlides, GetProjectDetail]);

  const GeminiSlideCall = async (prompt: string, index: number) => {
    try {
      console.log(`📡 Connecting to Gemini AI for slide ${index + 1}...`);
      const session = await GeminiAiModel.connect();
      console.log(`✅ Connected to Gemini AI session for slide ${index + 1}`);

      console.log(`📤 Sending prompt for slide ${index + 1}...`);
      console.log(`📝 Prompt length: ${prompt.length} characters`);
      await session.send(prompt);
      console.log(`✅ Prompt sent successfully for slide ${index + 1}`);

      let text = "";
      let messageCount = 0;

      console.log(`🔄 Starting to receive messages for slide ${index + 1}...`);
      // Read stream
      for await (const message of session.receive()) {
        messageCount++;
        console.log(
          `📨 Received message ${messageCount} for slide ${index + 1}, type: ${
            message.type
          }`
        );

        if (message.type === "serverContent") {
          const parts = message.modelTurn?.parts;
          console.log(`  - Parts count: ${parts?.length || 0}`);

          if (parts && parts.length > 0) {
            const newText = parts?.map((p) => p.text).join("");
            text += newText;
            console.log(
              `  - Text chunk length: ${newText.length}, Total text length: ${text.length}`
            );

            const finalText = text
              .replace(/```html/g, "")
              .replace(/```/g, "")
              .trim();

            // Live update the slider
            setSliders((prev: any[]) => {
              const updated = prev ? [...prev] : [];
              updated[index] = { code: finalText };
              return updated;
            });
          }

          if (message.turnComplete) {
            console.log(
              `✅ Slide ${
                index + 1
              } generation complete. Total messages: ${messageCount}`
            );
            console.log(`📊 Final text length: ${text.length}`);
            break; // important: exit loop when done
          }
        } else {
          console.log(`  - Message type: ${message.type}, not serverContent`);
        }
      }

      session.close();
      console.log(`🔌 Session closed for slide ${index + 1}`);
    } catch (err) {
      console.error(`❌ Error generating slide ${index + 1}:`, err);
      console.error(`❌ Error details:`, JSON.stringify(err, null, 2));
      throw err; // Re-throw to be caught by GenerateSlides
    }
  };

  useEffect(() => {
    if (isSlidesGenerated) SaveAllSlides();
  }, [isSlidesGenerated]);

  const SaveAllSlides = async () => {
    await setDoc(
      doc(firebaseDb, "projects", projectId ?? ""),
      {
        slides: sliders,
      },
      {
        merge: true,
      }
    );
  };

  const updateSliderCode = (updateSlideCode: string, index: number) => {
    setSliders((prev: any) => {
      const updated = [...prev];
      updated[index] = {
        ...updated[index],
        code: updateSlideCode,
      };
      return updated;
    });
    setIsSlidesGenerated(Date.now());
  };

  const exportAllIframesToPPT = async () => {
    if (!containerRef.current) {
      console.error("❌ Container ref not available");
      alert("Cannot export: Container not found");
      return;
    }

    const iframes = containerRef.current.querySelectorAll("iframe");
    if (iframes.length === 0) {
      console.error("❌ No slides found to export");
      alert("No slides available to export. Please generate slides first.");
      return;
    }

    setDownloadLoading(true);
    console.log(`📦 Starting PPT export for ${iframes.length} slides...`);

    try {
      const pptx = new PptxGenJS();

      // Set presentation properties
      pptx.layout = "LAYOUT_WIDE"; // 16:9 aspect ratio
      pptx.author = "AI PPT Generator";
      pptx.company = "AI PPT Generator";
      pptx.title = projectDetail?.userInputPrompt || "Generated Presentation";

      for (let i = 0; i < iframes.length; i++) {
        const iframe = iframes[i] as HTMLIFrameElement;
        const iframeDoc =
          iframe.contentDocument || iframe.contentWindow?.document;

        if (!iframeDoc) {
          console.warn(`⚠️ Cannot access iframe ${i + 1} document`);
          continue;
        }

        // Wait a bit for iframe to be ready
        await new Promise((resolve) => setTimeout(resolve, 100));

        // Grab the main slide element inside the iframe
        const slideNode =
          iframeDoc.querySelector("body > div") || iframeDoc.body;

        if (!slideNode) {
          console.warn(`⚠️ No slide content found in iframe ${i + 1}`);
          continue;
        }

        console.log(
          `📸 Converting slide ${i + 1}/${iframes.length} to image...`
        );

        try {
          // Convert slide to PNG image
          const dataUrl = await htmlToImage.toPng(slideNode as HTMLElement, {
            quality: 1,
            pixelRatio: 2, // Higher quality
            backgroundColor: "#ffffff",
          });

          // Add slide to presentation
          const slide = pptx.addSlide();
          slide.addImage({
            data: dataUrl,
            x: 0,
            y: 0,
            w: 10, // 16:9 aspect ratio (10 inches wide)
            h: 5.625, // 10 * 9/16 = 5.625 inches tall
          });

          console.log(`✅ Slide ${i + 1} added to PPT`);
        } catch (error) {
          console.error(`❌ Error converting slide ${i + 1}:`, error);
          // Continue with other slides even if one fails
        }
      }

      const fileName = `${
        projectDetail?.userInputPrompt?.substring(0, 30) || "Presentation"
      }_${Date.now()}.pptx`;
      console.log(`💾 Saving PPT file: ${fileName}`);
      await pptx.writeFile({ fileName });
      console.log(`✅ PPT export completed successfully!`);

      toast.success(`Successfully exported slides to ${fileName}`);
    } catch (error) {
      console.error("❌ Error during PPT export:", error);
      toast.error("Failed to export PPT. Please check the console for details.");
    } finally {
      setDownloadLoading(false);
    }
  };

    return (
        <div>
            <div className='flex items-center justify-center mt-4'>
                <Alert className='max-w-lg'>
                    <InfoIcon />
                    <AlertTitle>Info</AlertTitle>
                    <AlertDescription>
                        All slides from your outline will be generated at 800x500 resolution.
                    </AlertDescription>
                </Alert>
            </div>
            {loading && !projectDetail && (
                <div className='flex items-center justify-center h-screen'>
                    <div className='text-center'>
                        <Loader2 className='animate-spin mx-auto mb-4' size={48} />
                        <p className='text-lg font-semibold'>Loading project data...</p>
                        <p className='text-sm text-gray-500'>Please wait</p>
                    </div>
                </div>
            )}
            
            {!loading && projectDetail && (
            <div className='grid grid-cols-5 p-10 gap-10 '>
                <div className='col-span-2 h-[90vh] overflow-auto space-y-4'>
                    {/* AI Edit Guide */}
                    <AiEditGuide />
                    
                    {/* Outlines  */}
                    <OutlineSection outline={projectDetail?.outline ?? []}
                        handleUpdateOutline={() => console.log()}
                        loading={loading}
                    />
                </div>
                <div className='col-span-3 h-screen overflow-auto' ref={containerRef}>
                    {/* Manual Generate Button - Show if no slides and conditions are met */}
                    {!generatingSlides && (!sliders || sliders.length === 0) && projectDetail?.outline && projectDetail.outline.length > 0 && projectDetail?.designStyle && (
                        <div className='flex flex-col items-center justify-center p-10 gap-4'>
                            <p className='text-gray-500 text-center'>No slides generated yet.</p>
                            <Button 
                                onClick={() => {
                                    console.log("🖱️ Manual generate button clicked");
                                    if (projectDetail && projectDetail.outline && projectDetail.designStyle) {
                                        GenerateSlides();
                                    } else {
                                        alert("Missing outline or design style. Please check the console.");
                                    }
                                }}
                                size="lg"
                                className="bg-primary text-white"
                                disabled={generatingSlides || !projectDetail?.outline || !projectDetail?.designStyle}
                            >
                                {generatingSlides ? (
                                    <>
                                        <Loader2 className='animate-spin mr-2' size={20} />
                                        Generating...
                                    </>
                                ) : (
                                    <>
                                        Generate Slides <ArrowRight className="ml-2" />
                                    </>
                                )}
                            </Button>
                            <p className='text-xs text-gray-400 text-center max-w-md'>
                                Click to generate slides based on your outline and selected design style.
                            </p>
                        </div>
                    )}
                    
                    {/* Loading State */}
                    {generatingSlides && (
                        <div className='flex items-center justify-center p-10'>
                            <div className='text-center'>
                                <Loader2 className='animate-spin mx-auto mb-4' size={48} />
                                <p className='text-lg font-semibold'>Generating slides...</p>
                                <p className='text-sm text-gray-500'>This may take a few moments</p>
                                <p className='text-xs text-gray-400 mt-2'>Check console for progress</p>
                            </div>
                        </div>
                    )}
                    
                    {/* Generated Slides */}
                    {!generatingSlides && sliders && sliders.length > 0 && sliders.map((slide: any, index: number) => (
                        <SliderFrame slide={slide} key={index}
                            colors={projectDetail?.designStyle?.colors}
                            setUpdateSlider={(updateSlideCode: string) => updateSliderCode(updateSlideCode, index)}
                        />
                    ))}
                    
                    {/* No Slides and Missing Requirements */}
                    {!generatingSlides && (!sliders || sliders.length === 0) && (!projectDetail?.outline || projectDetail.outline.length === 0 || !projectDetail?.designStyle) && (
                        <div className='flex flex-col items-center justify-center p-10 gap-2'>
                            <p className='text-gray-500 text-center'>Cannot generate slides.</p>
                            {!projectDetail?.outline || projectDetail.outline.length === 0 ? (
                                <p className='text-sm text-red-500'>❌ Missing outline. Please go back and generate outline first.</p>
                            ) : null}
                            {!projectDetail?.designStyle ? (
                                <p className='text-sm text-red-500'>❌ Missing design style. Please go back and select a design style.</p>
                            ) : null}
                            <p className='text-xs text-gray-400 mt-4'>Please check the browser console for detailed error messages.</p>
                        </div>
                    )}
                </div>
                {/* Export button */}
                <Button onClick={exportAllIframesToPPT} size={'lg'} className='fixed bottom-6
            transform left-1/2 -translate-x-1/2'
                    disabled={downloadLoading}
                >
                    {downloadLoading ? <Loader2 className='animate-spin' /> : <FileDown />} Export PPT
                </Button>
            </div>
            )}
        </div>
    )
}

export default Editor;
